# Generated by Django 5.0.3 on 2026-07-26 09:20

import about.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutManifestoDifferentiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-graduation-cap', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('title', models.CharField(max_length=255, verbose_name='Differentiator Title')),
                ('description', models.TextField(verbose_name='Differentiator Description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Manifesto Differentiator Pill',
                'verbose_name_plural': 'Manifesto Differentiator Pills',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.IntegerField(default=0, verbose_name='Target Number for Animated Counter')),
                ('prefix', models.CharField(blank=True, default='', max_length=20, verbose_name="Value Prefix (e.g. '1:')")),
                ('suffix', models.CharField(blank=True, default='', max_length=20, verbose_name="Value Suffix (e.g. 'Yr', '%', '+')")),
                ('label', models.CharField(max_length=255, verbose_name='Primary Metric Label')),
                ('sub_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Sub Label')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Institutional Distinction Metric',
                'verbose_name_plural': 'Institutional Distinction Metrics',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearnMoreContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Want to Learn More About AIEMS?', max_length=255, verbose_name='Headline')),
                ('sub_heading', models.TextField(default='Connect directly with our admissions and academic counseling desk in Bardibas.', verbose_name='Sub Heading')),
                ('mail_id', models.CharField(default='info@aiems.edu.np', max_length=255, validators=[django.core.validators.EmailValidator(message='Please provide a valid institutional email address.')], verbose_name='Inquiry Email Address')),
                ('contact', models.CharField(default='9802113456', max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Counseling Hotline / Contact')),
                ('button_text', models.CharField(default='Be Part of Our Journey', max_length=100, verbose_name='CTA Button Text')),
                ('button_url', models.CharField(default='/contact-us', max_length=255, verbose_name='CTA Button Link')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Learn More Contact Information',
                'verbose_name_plural': 'Learn More Contact Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LearMoreContact',
        ),
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Executive Manifesto (About Intro)', 'verbose_name_plural': 'Executive Manifestos'},
        ),
        migrations.AlterModelOptions(
            name='aboutvisionbanner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Vision / Mission / Goal Pillar Card', 'verbose_name_plural': 'Vision / Mission / Goal Pillar Cards'},
        ),
        migrations.AlterModelOptions(
            name='aboutvisionitems',
            options={'ordering': ['id'], 'verbose_name': 'Pillar Checklist Bullet', 'verbose_name_plural': 'Pillar Checklist Bullets'},
        ),
        migrations.AlterModelOptions(
            name='aboutvisiontitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vision & Mission Section Title', 'verbose_name_plural': 'Vision & Mission Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='achievementbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Achievement Record', 'verbose_name_plural': 'Achievement Records'},
        ),
        migrations.AlterModelOptions(
            name='achievementtitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Achievement Section Title', 'verbose_name_plural': 'Achievement Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='campusoverview',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Learning Ecosystem Bento Facility', 'verbose_name_plural': 'Learning Ecosystem Bento Facilities'},
        ),
        migrations.AlterModelOptions(
            name='campustitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campus Ecosystem Section Title', 'verbose_name_plural': 'Campus Ecosystem Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='corevaluesbanner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Core Value Item', 'verbose_name_plural': 'Core Value Items'},
        ),
        migrations.AlterModelOptions(
            name='corevaluestitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Core Values Section Title', 'verbose_name_plural': 'Core Values Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='leadershipbanner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Leadership Profile', 'verbose_name_plural': 'Leadership Profiles'},
        ),
        migrations.AlterModelOptions(
            name='leadershiptitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Leadership Section Title', 'verbose_name_plural': 'Leadership Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='topbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Top Hero Banner', 'verbose_name_plural': 'Top Hero Banners'},
        ),
        migrations.AlterModelOptions(
            name='visionresearchbanner',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Research & Innovation Pillar', 'verbose_name_plural': 'Research & Innovation Pillars'},
        ),
        migrations.AlterModelOptions(
            name='visionresearchtitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Research & Innovation Section Title', 'verbose_name_plural': 'Research & Innovation Section Titles'},
        ),
        migrations.RemoveField(
            model_name='aboutbanner',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='badge_text',
            field=models.CharField(default='Institutional Origin & Legacy', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='charter_badge_degree',
            field=models.CharField(default='Rajarshi Janak University Degree', max_length=150, verbose_name='Charter Badge Subtext'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='charter_badge_subtitle',
            field=models.CharField(default='Chartered Academic Institution', max_length=150, verbose_name='Charter Badge Headline'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='charter_badge_title',
            field=models.CharField(default='Official Affiliation', max_length=100, verbose_name='Charter Badge Small Title'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='content_paragraph_1',
            field=models.TextField(default='Ankur Institute of Engineering and Management Studies (AIEMS) was founded with a single mission: to deliver standard, high-impact computing education in Madhesh Province. Operated under the prestigious academic charter of Rajarshi Janak University (RJU), AIEMS bridges university academic rigor with modern tech skills.', verbose_name='First Narrative Paragraph'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='content_paragraph_2',
            field=models.TextField(default='Our campus serves as a launchpad for future computer scientists, software architects, and tech entrepreneurs. We believe that true technical mastery emerges from combining university theory with intensive lab work.', verbose_name='Second Narrative Paragraph'),
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.about_banner_path, validators=[home.models.validate_image_file], verbose_name='Executive Photo (Collage Main Image)'),
        ),
        migrations.AddField(
            model_name='aboutvisionbanner',
            name='border_color_class',
            field=models.CharField(choices=[('border-brandPrimary', 'Brand Primary (Green)'), ('border-brandSecondary', 'Brand Secondary (Navy Blue)'), ('border-brandAccent', 'Brand Accent (Cyan)')], default='border-brandPrimary', max_length=50, verbose_name='Card Accent Left Border Color'),
        ),
        migrations.AddField(
            model_name='aboutvisionbanner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='aboutvisionbanner',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-eye', max_length=100, verbose_name='FontAwesome Icon Class'),
        ),
        migrations.AddField(
            model_name='aboutvisiontitle',
            name='badge_text',
            field=models.CharField(default='Institutional Pillars', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AddField(
            model_name='aboutvisiontitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='aboutvisiontitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='aboutvisiontitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='aboutvisiontitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='aboutvisiontitle',
            name='sub_heading',
            field=models.TextField(default='Guiding AIEMS towards standard technical benchmarks in computing education.', verbose_name='Section Subheading'),
        ),
        migrations.AddField(
            model_name='achievementtitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='achievementtitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='achievementtitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='achievementtitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='campusoverview',
            name='bento_span_class',
            field=models.CharField(choices=[('md:col-span-8', 'Wide Card (8 Columns)'), ('md:col-span-4', 'Standard Card (4 Columns)'), ('md:col-span-12', 'Full Width (12 Columns)')], default='md:col-span-4', max_length=50, verbose_name='Bento Grid Column Span'),
        ),
        migrations.AddField(
            model_name='campusoverview',
            name='category_badge',
            field=models.CharField(default='Interactive Education', max_length=100, verbose_name='Category Badge'),
        ),
        migrations.AddField(
            model_name='campusoverview',
            name='description',
            field=models.TextField(default='Ergonomically designed classrooms equipped with high-definition digital smartboards, visualizers, and acoustic treatment.', verbose_name='Facility Description'),
        ),
        migrations.AddField(
            model_name='campusoverview',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='campusoverview',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-chalkboard-user', max_length=100, verbose_name='FontAwesome Icon Class'),
        ),
        migrations.AddField(
            model_name='campusoverview',
            name='title',
            field=models.CharField(default='Smart Interactive Lecture Theatres', max_length=255, verbose_name='Facility Title'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='badge_text',
            field=models.CharField(default='Student Life & Environment', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='corevaluesbanner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='corevaluesbanner',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-laptop-code', max_length=100, verbose_name='FontAwesome Icon Class'),
        ),
        migrations.AddField(
            model_name='corevaluestitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='corevaluestitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='corevaluestitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='corevaluestitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='leadershipbanner',
            name='designation',
            field=models.CharField(default='Academic Administration', max_length=255, verbose_name='Designation Badge'),
        ),
        migrations.AddField(
            model_name='leadershipbanner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='leadershiptitle',
            name='badge_text',
            field=models.CharField(default='Visionary Direction', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AddField(
            model_name='leadershiptitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='leadershiptitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='leadershiptitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='leadershiptitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='leadershiptitle',
            name='sub_heading',
            field=models.TextField(default='Meet the academic leaders and administration shaping the future of AIEMS.', verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='badge_text',
            field=models.CharField(default='Institutional Profile & Institutional Identity', max_length=255, verbose_name='Top Badge Label'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='primary_btn_text',
            field=models.CharField(default='Explore Institutional Manifesto', max_length=100, verbose_name='Primary CTA Button Text'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='primary_btn_url',
            field=models.CharField(default='#about-intro', max_length=255, verbose_name='Primary CTA Button Link'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='secondary_btn_text',
            field=models.CharField(default='Vision & Core Values', max_length=100, verbose_name='Secondary CTA Button Text'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='secondary_btn_url',
            field=models.CharField(default='#vision-mission', max_length=255, verbose_name='Secondary CTA Button Link'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='visionresearchbanner',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='visionresearchtitle',
            name='badge_text',
            field=models.CharField(default='R&D Capabilities', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AddField(
            model_name='visionresearchtitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='visionresearchtitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='visionresearchtitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='visionresearchtitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='heading',
            field=models.CharField(default='A Foundation Built on University Synergy & Tech Mastery', max_length=255, verbose_name='Main Title'),
        ),
        migrations.AlterField(
            model_name='aboutvisionbanner',
            name='about_vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_vision_items', to='about.aboutvisiontitle', verbose_name='Vision Section Parent'),
        ),
        migrations.AlterField(
            model_name='aboutvisionbanner',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Pillar Narrative Copy'),
        ),
        migrations.AlterField(
            model_name='aboutvisionbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutvisionbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Pillar Title (e.g. Our Vision)'),
        ),
        migrations.AlterField(
            model_name='aboutvisionitems',
            name='about_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='about.aboutvisionbanner', verbose_name='Pillar Card Parent'),
        ),
        migrations.AlterField(
            model_name='aboutvisionitems',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Checklist Bullet Detail'),
        ),
        migrations.AlterField(
            model_name='aboutvisionitems',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutvisiontitle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutvisiontitle',
            name='heading',
            field=models.CharField(default='Vision, Mission & Goals', max_length=255, verbose_name='Section Heading'),
        ),
        migrations.AlterField(
            model_name='achievementbanner',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_items', to='about.achievementtitle', verbose_name='Achievement Title Group'),
        ),
        migrations.AlterField(
            model_name='achievementbanner',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='achievementbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='achievementbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='achievementtitle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='achievementtitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='campusoverview',
            name='campus_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_items', to='about.campustitle', verbose_name='Campus Section Parent'),
        ),
        migrations.AlterField(
            model_name='campusoverview',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campusoverview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.about_facility_path, validators=[home.models.validate_image_file], verbose_name='Background / Facility Image'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='heading',
            field=models.CharField(default='Our Learning Ecosystem & Facilities', max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='sub_heading',
            field=models.TextField(default='Designed to foster student focus, peer collaboration, and academic research in Bardibas.', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='corevaluesbanner',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Value Description'),
        ),
        migrations.AlterField(
            model_name='corevaluesbanner',
            name='core_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_items', to='about.corevaluestitle', verbose_name='Core Values Title Group'),
        ),
        migrations.AlterField(
            model_name='corevaluesbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='corevaluesbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Value Name (e.g. 🚀 Innovation)'),
        ),
        migrations.AlterField(
            model_name='corevaluesbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.about_icon_path, validators=[home.models.validate_image_file], verbose_name='Value Item Custom Icon Image'),
        ),
        migrations.AlterField(
            model_name='corevaluestitle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='corevaluestitle',
            name='heading',
            field=models.CharField(default='Our Guiding Core Values', max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='corevaluestitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.about_icon_path, validators=[home.models.validate_image_file], verbose_name='Section Background/Icon'),
        ),
        migrations.AlterField(
            model_name='corevaluestitle',
            name='sub_heading',
            field=models.TextField(default='We uphold these fundamental principles to guide our students, faculty, and administrative staff towards institutional excellence.', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='leadershipbanner',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Executive Statement / Quote Bio'),
        ),
        migrations.AlterField(
            model_name='leadershipbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='leadershipbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Full Name / Executive Title'),
        ),
        migrations.AlterField(
            model_name='leadershipbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.about_user_path, validators=[home.models.validate_image_file], verbose_name='Profile Portrait'),
        ),
        migrations.AlterField(
            model_name='leadershipbanner',
            name='leadership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_items', to='about.leadershiptitle', verbose_name='Leadership Section Parent'),
        ),
        migrations.AlterField(
            model_name='leadershiptitle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='leadershiptitle',
            name='heading',
            field=models.CharField(default='Institutional Leadership', max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='heading',
            field=models.CharField(default='Shaping Computer Science & Leadership in Nepal', max_length=255, verbose_name='Main Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.about_banner_path, validators=[home.models.validate_image_file], verbose_name='Hero Background Image'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='sub_heading',
            field=models.TextField(default='Discover Ankur Institute of Engineering and Management Studies — an institution dedicated to academic precision, hands-on software development, and transformative student opportunities in Bardibas.', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='visionresearchbanner',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='R&D Focus Description'),
        ),
        migrations.AlterField(
            model_name='visionresearchbanner',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='visionresearchbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='R&D Focus Title'),
        ),
        migrations.AlterField(
            model_name='visionresearchbanner',
            name='vision_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_research_items', to='about.visionresearchtitle', verbose_name='Research Section Parent'),
        ),
        migrations.AlterField(
            model_name='visionresearchtitle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='visionresearchtitle',
            name='heading',
            field=models.CharField(default='Vision for Research & Innovation', max_length=255, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='aboutmanifestodifferentiator',
            name='about_banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentiators', to='about.aboutbanner', verbose_name='Manifesto Parent'),
        ),
    ]
