# Generated by Django 5.0.3 on 2026-07-27 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutmanifestodifferentiator_aboutmetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbanner',
            name='badge_text',
            field=models.CharField(default='', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='charter_badge_degree',
            field=models.CharField(default='', max_length=150, verbose_name='Charter Badge Subtext'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='charter_badge_subtitle',
            field=models.CharField(default='', max_length=150, verbose_name='Charter Badge Headline'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='charter_badge_title',
            field=models.CharField(default='', max_length=100, verbose_name='Charter Badge Small Title'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='content_paragraph_1',
            field=models.TextField(default='', verbose_name='First Narrative Paragraph'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='content_paragraph_2',
            field=models.TextField(default='', verbose_name='Second Narrative Paragraph'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Main Title'),
        ),
        migrations.AlterField(
            model_name='aboutvisiontitle',
            name='badge_text',
            field=models.CharField(default='', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AlterField(
            model_name='aboutvisiontitle',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Section Heading'),
        ),
        migrations.AlterField(
            model_name='aboutvisiontitle',
            name='sub_heading',
            field=models.TextField(default='', verbose_name='Section Subheading'),
        ),
        migrations.AlterField(
            model_name='campusoverview',
            name='category_badge',
            field=models.CharField(default='', max_length=100, verbose_name='Category Badge'),
        ),
        migrations.AlterField(
            model_name='campusoverview',
            name='description',
            field=models.TextField(default='', verbose_name='Facility Description'),
        ),
        migrations.AlterField(
            model_name='campusoverview',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Facility Title'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='badge_text',
            field=models.CharField(default='', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='sub_heading',
            field=models.TextField(default='', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='corevaluesbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Value Name (e.g. Innovation)'),
        ),
        migrations.AlterField(
            model_name='corevaluestitle',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='corevaluestitle',
            name='sub_heading',
            field=models.TextField(default='', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='leadershipbanner',
            name='designation',
            field=models.CharField(default='', max_length=255, verbose_name='Designation Badge'),
        ),
        migrations.AlterField(
            model_name='leadershiptitle',
            name='badge_text',
            field=models.CharField(default='', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AlterField(
            model_name='leadershiptitle',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='leadershiptitle',
            name='sub_heading',
            field=models.TextField(default='', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='learnmorecontact',
            name='button_text',
            field=models.CharField(default='', max_length=100, verbose_name='CTA Button Text'),
        ),
        migrations.AlterField(
            model_name='learnmorecontact',
            name='contact',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Counseling Hotline / Contact'),
        ),
        migrations.AlterField(
            model_name='learnmorecontact',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='learnmorecontact',
            name='mail_id',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.EmailValidator(message='Please provide a valid institutional email address.')], verbose_name='Inquiry Email Address'),
        ),
        migrations.AlterField(
            model_name='learnmorecontact',
            name='sub_heading',
            field=models.TextField(default='', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='badge_text',
            field=models.CharField(default='', max_length=255, verbose_name='Top Badge Label'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Main Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='primary_btn_text',
            field=models.CharField(default='', max_length=100, verbose_name='Primary CTA Button Text'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='secondary_btn_text',
            field=models.CharField(default='', max_length=100, verbose_name='Secondary CTA Button Text'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='sub_heading',
            field=models.TextField(default='', verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='visionresearchtitle',
            name='badge_text',
            field=models.CharField(default='', max_length=255, verbose_name='Section Badge Label'),
        ),
        migrations.AlterField(
            model_name='visionresearchtitle',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='Heading'),
        ),
    ]
