# Generated by Django 5.0.3 on 2025-08-17 10:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_contactus_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_programs', to='home.program')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_outcomes', to='home.program')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOutcomeChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('career_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_outcomes', to='program.careeroutcomes')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='home.program')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetailChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('credit_hours', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='program.coursedetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEntryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_requirements', to='home.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSummaryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('title', models.CharField(choices=[('course name', 'Course Name'), ('course code', 'Course Code'), ('course duration', 'Course Duration'), ('credit hours', 'Credit Hours'), ('entry requirement', 'Entry Requirement'), ('intake', 'Intake'), ('time', 'Time'), ('accreditation', 'Accreditation')], default='', max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_summary', to='home.program')),
            ],
        ),
    ]
