# Generated by Django 5.0.3 on 2025-08-24 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_applyforcoursebanner_applyforpositionbanner'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.CreateModel(
            name='ProgramBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_banner', to='home.program')),
            ],
        ),
    ]
