# Generated by Django 5.0.3 on 2026-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_aboutprogram_image_programbannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutprogram',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='small_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
