# Generated by Django 5.0.3 on 2026-07-28 14:54

import django.db.models.deletion
import django.utils.timezone
import home.models
import program.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_footerlink_options_footerlink_category_and_more'),
        ('program', '0003_alter_aboutprogram_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careeroutcomechild',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='coursedetailchild',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='programsummarypoints',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='aboutprogram',
            name='charter_badge_subtext',
            field=models.CharField(default='Approved by Ministry of Education, Nepal', max_length=255, verbose_name='Charter Badge Subtext'),
        ),
        migrations.AddField(
            model_name='aboutprogram',
            name='charter_badge_tag',
            field=models.CharField(default='Official Affiliation', max_length=100, verbose_name='Charter Badge Tag'),
        ),
        migrations.AddField(
            model_name='aboutprogram',
            name='charter_badge_title',
            field=models.CharField(default='Rajarshi Janak University', max_length=255, verbose_name='Charter Badge Headline'),
        ),
        migrations.AddField(
            model_name='aboutprogram',
            name='content_paragraph_2',
            field=models.TextField(blank=True, default='', verbose_name='Second Narrative Paragraph'),
        ),
        migrations.AddField(
            model_name='careeroutcomechild',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='careeroutcomechild',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-code', max_length=100, verbose_name='FontAwesome Icon Class'),
        ),
        migrations.AddField(
            model_name='careeroutcomechild',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Role Focus Area'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='credit_summary_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Summary Text (e.g. 15 Credit Hours | 5 Courses)'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='elective_stream_title',
            field=models.CharField(blank=True, default='Fill / Select Elective Stream', max_length=255, verbose_name='Elective Section Header'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='has_electives',
            field=models.BooleanField(default=False, verbose_name='Contains Elective Selection Stream?'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Semester Heading (e.g. Semester I — Core Foundation)'),
        ),
        migrations.AddField(
            model_name='coursedetailchild',
            name='course_type',
            field=models.CharField(blank=True, default='Core Theory + Lab', max_length=100, verbose_name='Course Type Badge Label'),
        ),
        migrations.AddField(
            model_name='coursedetailchild',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Course/Elective Short Description'),
        ),
        migrations.AddField(
            model_name='coursedetailchild',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursedetailchild',
            name='is_elective',
            field=models.BooleanField(default=False, verbose_name='Is Elective Option?'),
        ),
        migrations.AddField(
            model_name='programentryrequirement',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-user-graduate', max_length=100, verbose_name='FontAwesome Icon Class'),
        ),
        migrations.AddField(
            model_name='programsummarypoints',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programsummarypoints',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-clock', max_length=100, verbose_name='FontAwesome Icon Class'),
        ),
        migrations.AddField(
            model_name='programsummarypoints',
            name='sub_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sub label (e.g. 8 Semesters)'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='content',
            field=models.TextField(default='', verbose_name='First Narrative Paragraph'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='small_title',
            field=models.CharField(default='Academic Flagship', max_length=255),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Role Title'),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='content',
            field=models.TextField(default='', verbose_name='Section Intro Copy'),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='title',
            field=models.CharField(default='Graduate Career Roles', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='semester',
            field=models.CharField(max_length=100, verbose_name='Semester (e.g. 1, 5, 6)'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='programbannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='content',
            field=models.TextField(default='', verbose_name='General Entry Requirement Overview'),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='title',
            field=models.CharField(default='Entrance Eligibility Criteria', max_length=255),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file]),
        ),
        migrations.CreateModel(
            name='AboutProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Feature Headline')),
                ('description', models.TextField(verbose_name='Feature Description')),
                ('icon_class', models.CharField(default='fa-solid fa-code', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('about_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='program.aboutprogram')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEntryRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Checklist Rule Copy')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='program.programentryrequirement')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramIndustryCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Partner Name (e.g. EC-Council)')),
                ('category_badge', models.CharField(max_length=100, verbose_name='Category Badge (e.g. Cybersecurity Partner)')),
                ('badge_color_class', models.CharField(default='text-primary bg-primary/10', max_length=100, verbose_name='Tailwind Color Badge Utility Class')),
                ('description', models.TextField(verbose_name='Certification Description')),
                ('track_label', models.CharField(max_length=100, verbose_name='Track Tag (e.g. CEH v12 Track)')),
                ('icon_class', models.CharField(default='fa-solid fa-certificate', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_certifications', to='home.program')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
