# Generated by Django 5.0.3 on 2026-07-28 18:30

import django.db.models.deletion
import django.utils.timezone
import home.models
import program.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_navbarlink'),
        ('program', '0004_alter_careeroutcomechild_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutprogram',
            options={'ordering': ['-created_at'], 'verbose_name': 'Program Narrative & Overview', 'verbose_name_plural': 'Program Narratives & Overviews'},
        ),
        migrations.AlterModelOptions(
            name='aboutprogramfeature',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Program Feature Highlight', 'verbose_name_plural': 'Program Feature Highlights'},
        ),
        migrations.AlterModelOptions(
            name='careeroutcomechild',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Graduate Career Role', 'verbose_name_plural': 'Graduate Career Roles'},
        ),
        migrations.AlterModelOptions(
            name='careeroutcomes',
            options={'ordering': ['-created_at'], 'verbose_name': 'Career Outlook Group', 'verbose_name_plural': 'Career Outlook Groups'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Semester Curriculum Group', 'verbose_name_plural': 'Semester Curriculum Groups'},
        ),
        migrations.AlterModelOptions(
            name='coursedetailchild',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Curriculum Subject Item', 'verbose_name_plural': 'Curriculum Subject Items'},
        ),
        migrations.AlterModelOptions(
            name='programbannerimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Program Banner Image', 'verbose_name_plural': 'Program Banner Images'},
        ),
        migrations.AlterModelOptions(
            name='programentryrequirement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrance Eligibility Section', 'verbose_name_plural': 'Entrance Eligibility Sections'},
        ),
        migrations.AlterModelOptions(
            name='programentryrequirementitem',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Eligibility Checklist Item', 'verbose_name_plural': 'Eligibility Checklist Items'},
        ),
        migrations.AlterModelOptions(
            name='programindustrycertification',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Industry Certification Co-Track', 'verbose_name_plural': 'Industry Certification Co-Tracks'},
        ),
        migrations.AlterModelOptions(
            name='programsummarypoints',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Program Metric Highlight', 'verbose_name_plural': 'Program Metric Highlights'},
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='charter_badge_subtext',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Charter Badge Subtext'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='charter_badge_tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Charter Badge Tag Label'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='charter_badge_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Charter Badge Headline'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='content',
            field=models.TextField(default='', verbose_name='Primary Narrative Paragraph'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='content_paragraph_2',
            field=models.TextField(blank=True, default='', verbose_name='Secondary Narrative Paragraph'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file], verbose_name='Overview Feature Photo'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_programs', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='small_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Small Section Tag Label'),
        ),
        migrations.AlterField(
            model_name='aboutprogram',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Main Headline'),
        ),
        migrations.AlterField(
            model_name='aboutprogramfeature',
            name='about_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='program.aboutprogram', verbose_name='Parent Narrative Record'),
        ),
        migrations.AlterField(
            model_name='aboutprogramfeature',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutprogramfeature',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='career_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_outcomes', to='program.careeroutcomes', verbose_name='Parent Career Group'),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file], verbose_name='Custom Icon Image'),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Role Specialization / Scope'),
        ),
        migrations.AlterField(
            model_name='careeroutcomechild',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Role Title'),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Section Intro Copy'),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_outcomes', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='careeroutcomes',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Section Title'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='credit_summary_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Credit Summary Badge (e.g. '15 Credit Hours')"),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='elective_stream_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Elective Section Title'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='semester',
            field=models.CharField(max_length=100, verbose_name="Semester Identifier (e.g. '1', '5')"),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Semester Title (e.g. 'Semester I — Foundation')"),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='course_code',
            field=models.CharField(max_length=50, verbose_name='Course Code (e.g. CSC109)'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='program.coursedetail', verbose_name='Parent Semester Group'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='course_name',
            field=models.CharField(max_length=255, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='course_type',
            field=models.CharField(blank=True, default='Core Theory + Lab', max_length=100, verbose_name='Course Type Badge'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='credit_hours',
            field=models.PositiveIntegerField(default=3, verbose_name='Credit Hours'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Elective Subject Description'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='coursedetailchild',
            name='is_elective',
            field=models.BooleanField(default=False, verbose_name='Is Elective Subject?'),
        ),
        migrations.AlterField(
            model_name='programbannerimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='programbannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file], verbose_name='Hero Banner Media Asset'),
        ),
        migrations.AlterField(
            model_name='programbannerimage',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_banner', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='content',
            field=models.TextField(default='', verbose_name='General Prerequisite Overview Copy'),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file], verbose_name='Custom Section Icon Asset'),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_requirements', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='programentryrequirement',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Section Title Label'),
        ),
        migrations.AlterField(
            model_name='programentryrequirementitem',
            name='content',
            field=models.TextField(verbose_name='Checklist Requirement Rule'),
        ),
        migrations.AlterField(
            model_name='programentryrequirementitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='programentryrequirementitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='programentryrequirementitem',
            name='entry_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='program.programentryrequirement', verbose_name='Parent Requirement Group'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='badge_color_class',
            field=models.CharField(default='text-primary bg-primary/10', max_length=100, verbose_name='Tailwind Badge Style Class'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='category_badge',
            field=models.CharField(max_length=100, verbose_name='Category Badge'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='partner_name',
            field=models.CharField(max_length=255, verbose_name='Partner / Vendor Name'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_certifications', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='programindustrycertification',
            name='track_label',
            field=models.CharField(max_length=100, verbose_name='Track Tag'),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=program.models.program_asset_path, validators=[home.models.validate_image_file], verbose_name='Custom Icon Image'),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_summary', to='home.program', verbose_name='Associated Program'),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='sub_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Sub label (e.g. '8 Semesters')"),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='title',
            field=models.CharField(choices=[('course name', 'Course Name'), ('course code', 'Course Code'), ('course duration', 'Course Duration'), ('credit hours', 'Credit Hours'), ('entry requirement', 'Entry Requirement'), ('intake', 'Intake'), ('time', 'Time'), ('accreditation', 'Accreditation')], default='', max_length=255, verbose_name='Metric Label / Category'),
        ),
        migrations.AlterField(
            model_name='programsummarypoints',
            name='value',
            field=models.CharField(max_length=255, verbose_name="Metric Highlight Value (e.g. '4 Years')"),
        ),
    ]
