# Generated by Django 5.0.3 on 2026-08-02 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_alter_aboutprogram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetailChildElectiveOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Elective Course Name')),
                ('course_code', models.CharField(max_length=50, verbose_name='Elective Course Code (e.g. SCIT 421)')),
                ('credit_hours', models.PositiveIntegerField(default=3, verbose_name='Credit Hours')),
                ('description', models.TextField(blank=True, default='', verbose_name='Elective Course Description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('course_detail_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_options', to='program.coursedetailchild', verbose_name='Parent Elective Subject')),
            ],
            options={
                'verbose_name': 'Elective Course Option',
                'verbose_name_plural': 'Elective Course Options',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
