# Generated by Django 5.0.3 on 2026-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_coursedetailchildelectiveoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailchild',
            name='credit_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Credit Hours (Optional)'),
        ),
        migrations.AlterField(
            model_name='coursedetailchildelectiveoption',
            name='credit_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Credit Hours (Optional)'),
        ),
    ]
