# Generated by Django 5.0.3 on 2026-08-31 16:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.models
import training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('structured_data', models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)')),
                ('badge_text', models.CharField(default='Zero Coding or Technical Background Required', max_length=255, verbose_name='Top Hero Badge Label')),
                ('heading', models.CharField(default='Bridge Into Tech: Practical IT & AI Training for Non-Tech Students', max_length=255, verbose_name='Main Headline')),
                ('sub_heading', models.TextField(default='Tailored exclusively for Management, Humanities, Arts, Education, and Law students. Master modern AI tools, coding logic, web essentials, cybersecurity, and cloud workspace through 100% hands-on lab sessions at AIEMS Bardibas.', verbose_name='Hero Narrative Subtext')),
                ('image', models.ImageField(blank=True, null=True, upload_to=training.models.training_banner_path, validators=[home.models.validate_image_file], verbose_name='Hero Background Image')),
                ('primary_btn_text', models.CharField(default='Reserve Your Seat', max_length=100, verbose_name='Primary CTA Button Text')),
                ('primary_btn_url', models.CharField(default='#trainingLeadForm', max_length=255, verbose_name='Primary CTA Link Target')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Training Page Hero Banner',
                'verbose_name_plural': 'Training Page Hero Banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplicationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(db_index=True, default=training.models.generate_training_ref_id, max_length=50, unique=True, verbose_name='Registration Reference ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Student Full Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=50, verbose_name='Gender Identity')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Mobile Phone Number')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50, verbose_name='WhatsApp Number')),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('academic_stream', models.CharField(max_length=255, verbose_name='Current Academic Background / Stream')),
                ('institution', models.CharField(max_length=255, verbose_name='Previous School / College / City')),
                ('selected_modules', models.JSONField(default=list, verbose_name='Enrolled Training Modules (JSON List)')),
                ('time_slot', models.CharField(max_length=100, verbose_name='Preferred Time Slot')),
                ('training_mode', models.CharField(default='Physical Lab at AIEMS Campus, Bardibas', max_length=150, verbose_name='Delivery Mode')),
                ('experience_level', models.CharField(blank=True, default='', max_length=150, verbose_name='Computer Comfort Level')),
                ('learning_goal', models.TextField(blank=True, default='', verbose_name='Specific Questions or Goals')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Submitted Timestamp')),
            ],
            options={
                'verbose_name': 'Captured Training Registration Lead',
                'verbose_name_plural': 'Captured Training Registration Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ref_id'], name='training_tr_ref_id_ce6c7b_idx'), models.Index(fields=['phone'], name='training_tr_phone_0c0fbc_idx'), models.Index(fields=['-created_at'], name='training_tr_created_0a985c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingCurriculumModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Module Title (e.g., 1. AI Fundamentals)')),
                ('description', models.TextField(verbose_name='Module Description (Plain-English Summary)')),
                ('icon_class', models.CharField(default='fa-solid fa-brain', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Module Active / Visible?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Curriculum Module Track',
                'verbose_name_plural': 'Curriculum Module Tracks',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSidebarPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Perk Headline (e.g., Dedicated Computer Lab Setup)')),
                ('icon_class', models.CharField(default='fa-solid fa-check', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Sidebar Student Perk',
                'verbose_name_plural': 'Sidebar Student Perks',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingStreamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Academic Stream Option Name')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Option Visible?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_options', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Form Academic Stream Option',
                'verbose_name_plural': 'Form Academic Stream Options',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=100, verbose_name='Time Range Label (e.g., 4:00 PM - 5:00 PM)')),
                ('slot_tag', models.CharField(default='Evening Slot A', max_length=100, verbose_name='Slot Sub-Tag (e.g., Evening Slot A, Twilight Slot C)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Slot Active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Daily Evening Time Slot',
                'verbose_name_plural': 'Daily Evening Time Slots',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
