# Generated by Django 5.0.3 on 2026-09-01 04:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDeliveryMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Delivery Mode Option Name (e.g., Physical Lab at AIEMS Campus)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Option Active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_modes', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Form Delivery Mode Option',
                'verbose_name_plural': 'Form Delivery Mode Options',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Computer Experience Level Name (e.g., Absolute Beginner)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Option Active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_levels', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Form Experience Level Option',
                'verbose_name_plural': 'Form Experience Level Options',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
