# Generated by Django 5.0.3 on 2026-09-01 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingdeliverymode_trainingexperiencelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplicationlead',
            name='timeframe',
            field=models.CharField(blank=True, default='3 Months (Certificate Track)', max_length=150, verbose_name='Chosen Timeframe / Duration'),
        ),
        migrations.CreateModel(
            name='TrainingTimeframeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Training Timeframe / Duration Option (e.g. '3 Months (Certificate Track)')")),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Option Active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('training_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeframe_options', to='training.trainingpagebanner', verbose_name='Parent Training Page')),
            ],
            options={
                'verbose_name': 'Form Timeframe / Duration Option',
                'verbose_name_plural': 'Form Timeframe / Duration Options',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
