# Generated by Django 5.0.3 on 2025-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityimage',
            name='campus_facility',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='news_event',
        ),
        migrations.RemoveField(
            model_name='aboutbanner',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='campusfacility',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='campusfacility',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='newsevent',
            name='sub_heading',
        ),
        migrations.AddField(
            model_name='aboutbanner',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campusfacility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AboutItem',
        ),
        migrations.DeleteModel(
            name='FacilityImage',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
