# Generated by Django 5.0.3 on 2025-05-03 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutbannertitle_admissioncontactdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('mail_id', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
