# Generated by Django 5.0.3 on 2025-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactus_position_applycourse_applyposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
