# Generated by Django 5.0.3 on 2025-08-24 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactus_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForCourseBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyForPositionBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
