# Generated by Django 5.0.3 on 2026-07-20 05:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_applyforcoursebanner_applyforpositionbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'About Banner Item', 'verbose_name_plural': 'About Banner Items'},
        ),
        migrations.AlterModelOptions(
            name='aboutbannertitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'About Banner Title', 'verbose_name_plural': 'About Banner Titles'},
        ),
        migrations.AlterModelOptions(
            name='admissioncontactdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admission Contact Detail', 'verbose_name_plural': 'Admission Contact Details'},
        ),
        migrations.AlterModelOptions(
            name='admissioncriteria',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admission Criteria Rule', 'verbose_name_plural': 'Admission Criteria Rules'},
        ),
        migrations.AlterModelOptions(
            name='admissiondetailtitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admission Detail Section Title', 'verbose_name_plural': 'Admission Detail Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='applycourse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Program Course Admission Application', 'verbose_name_plural': 'Program Course Admission Applications'},
        ),
        migrations.AlterModelOptions(
            name='applyforcoursebanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application Course Landing Banner', 'verbose_name_plural': 'Application Course Landing Banners'},
        ),
        migrations.AlterModelOptions(
            name='applyforpositionbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application Position Landing Banner', 'verbose_name_plural': 'Application Position Landing Banners'},
        ),
        migrations.AlterModelOptions(
            name='applyjobdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Careers Section Information', 'verbose_name_plural': 'Careers Section Information'},
        ),
        migrations.AlterModelOptions(
            name='applyposition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Career Job Application Form Submission', 'verbose_name_plural': 'Career Job Application Form Submissions'},
        ),
        migrations.AlterModelOptions(
            name='campusfacility',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campus Facility', 'verbose_name_plural': 'Campus Facilities'},
        ),
        migrations.AlterModelOptions(
            name='campustitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campus Section Title', 'verbose_name_plural': 'Campus Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message Log', 'verbose_name_plural': 'Contact Message Logs'},
        ),
        migrations.AlterModelOptions(
            name='newsevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Event', 'verbose_name_plural': 'News Events'},
        ),
        migrations.AlterModelOptions(
            name='newstitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Section Title', 'verbose_name_plural': 'News Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Career Vacancy Job Position', 'verbose_name_plural': 'Career Vacancy Job Positions'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at'], 'verbose_name': 'Academic Program', 'verbose_name_plural': 'Academic Programs'},
        ),
        migrations.AlterModelOptions(
            name='programtitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Program Section Title', 'verbose_name_plural': 'Program Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='teamfaculty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Team Department/Faculty Group', 'verbose_name_plural': 'Team Department/Faculty Groups'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Team Member Profile', 'verbose_name_plural': 'Team Member Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teamtitle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Team Section Title', 'verbose_name_plural': 'Team Section Titles'},
        ),
        migrations.AlterModelOptions(
            name='topbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Top Banner', 'verbose_name_plural': 'Top Banners'},
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='applyforcoursebanner',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='applyforcoursebanner',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='applyforcoursebanner',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='applyforcoursebanner',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='applyforpositionbanner',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='applyforpositionbanner',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='applyforpositionbanner',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='applyforpositionbanner',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='campustitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='programtitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='programtitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='programtitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='programtitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='teamtitle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='teamtitle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='teamtitle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='teamtitle',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='structured_data',
            field=models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='about_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_banner_items', to='home.aboutbannertitle', verbose_name='About Banner Title Group'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='mail_id',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='admission_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria_items', to='home.admissiondetailtitle', verbose_name='Admission Detail Title Parent'),
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Criteria Rule Description'),
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='sub_content',
            field=models.CharField(max_length=255, verbose_name='Sub Content Label'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Applied At'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=255, verbose_name='Gender Identity'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Previous High School / 12th Institution'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Applicant Name'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_course_program', to='home.program', verbose_name='Applied Program Course'),
        ),
        migrations.AlterField(
            model_name='applyforcoursebanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='applyforcoursebanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='applyforcoursebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.top_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='applyforcoursebanner',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applyforpositionbanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='applyforpositionbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='applyforpositionbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.top_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='applyforpositionbanner',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='HR Contact Number'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='mail_id',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='HR Email'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Applied At'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=home.models.apply_position_resume_path, validators=[home.models.validate_document_file], verbose_name='CV / Resume PDF Document'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=255, verbose_name='Gender Identity'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Cover Message'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Job Candidate Name'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_position', to='home.position', verbose_name='Applied Vacancy Position'),
        ),
        migrations.AlterField(
            model_name='campusfacility',
            name='campus_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_items', to='home.campustitle', verbose_name='Campus Title Group'),
        ),
        migrations.AlterField(
            model_name='campusfacility',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campusfacility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.campus_facility_path, validators=[home.models.validate_image_file], verbose_name='Facility Image'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City Address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.CharField(help_text='Support formatting standard (+97798XXXXXXXX).', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted Timestamp'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Inquiry Description Text'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Inquirer Name'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='news_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='home.newstitle', verbose_name='News Title Group'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Vacancy Job Position Name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='program',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon_image',
            field=models.ImageField(upload_to=home.models.program_icon_path, validators=[home.models.validate_image_file], verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='home.programtitle', verbose_name='Program Title Group'),
        ),
        migrations.AlterField(
            model_name='program',
            name='sub_content',
            field=models.TextField(verbose_name='Sub Content Summary'),
        ),
        migrations.AlterField(
            model_name='programtitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='programtitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='programtitle',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='teamfaculty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='teamfaculty',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='teamfaculty',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='teamfaculty',
            name='team_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_items', to='home.teamtitle', verbose_name='Team Title Group'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Designation Title'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_items', to='home.teamfaculty', verbose_name='Department Faculty Assignment'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='message',
            field=models.TextField(default='', verbose_name='Leadership Message Statement'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.team_member_path, validators=[home.models.validate_image_file], verbose_name='Profile Portrait'),
        ),
        migrations.AlterField(
            model_name='teamtitle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='teamtitle',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='teamtitle',
            name='sub_heading',
            field=models.CharField(max_length=255, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(upload_to=home.models.top_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='sub_heading',
            field=models.TextField(verbose_name='Sub Heading'),
        ),
        migrations.AddIndex(
            model_name='aboutbanner',
            index=models.Index(fields=['-created_at'], name='home_aboutb_created_66015d_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutbannertitle',
            index=models.Index(fields=['-created_at'], name='home_aboutb_created_64a557_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncontactdetail',
            index=models.Index(fields=['-created_at'], name='home_admiss_created_4bb419_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncriteria',
            index=models.Index(fields=['-created_at'], name='home_admiss_created_d3f148_idx'),
        ),
        migrations.AddIndex(
            model_name='admissiondetailtitle',
            index=models.Index(fields=['-created_at'], name='home_admiss_created_ad9e15_idx'),
        ),
        migrations.AddIndex(
            model_name='applycourse',
            index=models.Index(fields=['-created_at'], name='home_applyc_created_255603_idx'),
        ),
        migrations.AddIndex(
            model_name='applyforcoursebanner',
            index=models.Index(fields=['-created_at'], name='home_applyf_created_bbfafb_idx'),
        ),
        migrations.AddIndex(
            model_name='applyforpositionbanner',
            index=models.Index(fields=['-created_at'], name='home_applyf_created_0cf7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='applyjobdetail',
            index=models.Index(fields=['-created_at'], name='home_applyj_created_fc6494_idx'),
        ),
        migrations.AddIndex(
            model_name='applyposition',
            index=models.Index(fields=['-created_at'], name='home_applyp_created_542d52_idx'),
        ),
        migrations.AddIndex(
            model_name='campusfacility',
            index=models.Index(fields=['-created_at'], name='home_campus_created_f148e7_idx'),
        ),
        migrations.AddIndex(
            model_name='campustitle',
            index=models.Index(fields=['-created_at'], name='home_campus_created_8cd0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contactus',
            index=models.Index(fields=['-created_at'], name='home_contac_created_aa13b7_idx'),
        ),
        migrations.AddIndex(
            model_name='newsevent',
            index=models.Index(fields=['-created_at'], name='home_newsev_created_6b7f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='newsevent',
            index=models.Index(fields=['date'], name='home_newsev_date_6fd903_idx'),
        ),
        migrations.AddIndex(
            model_name='newstitle',
            index=models.Index(fields=['-created_at'], name='home_newsti_created_9f68a8_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['-created_at'], name='home_progra_created_c05eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='programtitle',
            index=models.Index(fields=['-created_at'], name='home_progra_created_c7548b_idx'),
        ),
        migrations.AddIndex(
            model_name='teamfaculty',
            index=models.Index(fields=['-created_at'], name='home_teamfa_created_f29b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['-created_at'], name='home_teamme_created_5b6af6_idx'),
        ),
        migrations.AddIndex(
            model_name='teamtitle',
            index=models.Index(fields=['-created_at'], name='home_teamti_created_1589da_idx'),
        ),
        migrations.AddIndex(
            model_name='topbanner',
            index=models.Index(fields=['-created_at'], name='home_topban_created_698445_idx'),
        ),
    ]
