# Generated by Django 5.0.3 on 2026-07-20 12:23

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_aboutbanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload the footer branding logo. Best dimensions: 160x70 px.', null=True, upload_to=home.models.footer_logo_path, validators=[home.models.validate_image_file], verbose_name='Footer Logo')),
                ('branding_description', models.TextField(blank=True, default='', help_text='Centralized branding description shown dynamically in the footer text layout.', null=True, verbose_name='Branding Description')),
                ('facebook_url', models.URLField(blank=True, help_text='Complete URL referencing the official institutional Facebook page.', null=True, verbose_name='Facebook URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Complete URL referencing the official institutional LinkedIn profile.', null=True, verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Complete URL referencing the official institutional Instagram profile.', null=True, verbose_name='Instagram URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Footer Configuration',
                'verbose_name_plural': 'Footer Configurations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_footer_created_9b683c_idx')],
            },
        ),
    ]
