# Generated by Django 5.0.3 on 2026-07-20 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_footerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The text label displayed on the public navigation panel.', max_length=255, verbose_name='Link Label')),
                ('url', models.CharField(help_text="Accepts relative paths (e.g. '/about-us') or absolute URLs (e.g. 'https://example.com').", max_length=500, verbose_name='URL / Path')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ascending numeric order to sequence links on the layout.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility state on the navigation panel without deleting the database record.', verbose_name='Is Active')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text="Applies target='_blank' behavior to the anchor tag on the public interface.", verbose_name='Open In New Tab')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('footer_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='home.footerconfig', verbose_name='Footer Configuration Parent')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='home_footer_display_4e0c60_idx'), models.Index(fields=['is_active'], name='home_footer_is_acti_d357f4_idx')],
            },
        ),
    ]
