# Generated by Django 5.0.3 on 2026-07-21 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('structured_data', models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)')),
                ('page_key', models.CharField(help_text="Programmatic unique identifier (e.g., 'privacy-policy', 'terms-and-conditions').", max_length=100, unique=True, verbose_name='Page Key')),
                ('title', models.CharField(max_length=255, verbose_name='Page Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page Subtitle')),
                ('content_json', models.JSONField(blank=True, help_text='Structured representation supporting headings, sections, and paragraphs.', null=True, verbose_name='Structured Content (JSON)')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle rendering availability on the application routing layout.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Dynamic Page Content',
                'verbose_name_plural': 'Dynamic Page Contents',
                'ordering': ['page_key'],
                'indexes': [models.Index(fields=['page_key'], name='home_dynami_page_ke_fcfea5_idx'), models.Index(fields=['is_active'], name='home_dynami_is_acti_62fca3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier used for frontend filtering.', max_length=255, unique=True, verbose_name='Slug')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ascending order index used to sort categories.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='home_faqcat_display_f8eb74_idx'), models.Index(fields=['slug'], name='home_faqcat_slug_4bf5ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility state on the client interface.', verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ascending order index used to sequence entries within the category.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='home.faqcategory', verbose_name='Category Parent')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='home_faqite_display_6f1c8f_idx'), models.Index(fields=['is_active'], name='home_faqite_is_acti_1be592_idx')],
            },
        ),
    ]
