# Generated by Django 5.0.3 on 2026-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dynamicpagecontent_faqcategory_faqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncriteria',
            name='content',
            field=models.CharField(help_text="e.g., '12 years of schooling in Science stream with 2.2 CGPA and RJU Entrance exam clearance.'", max_length=255, verbose_name='Criteria Rule Description'),
        ),
    ]
