# Generated by Django 5.0.3 on 2026-07-27 13:32

import django.core.validators
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_admissioncriteria_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementTickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_label', models.CharField(default='Notice', max_length=100, verbose_name='Badge Label (e.g. Inaugural Year, Admission)')),
                ('text_content', models.CharField(max_length=500, verbose_name='Announcement Headline Copy')),
                ('target_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Action Link (Optional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Announcement Ticker Item',
                'verbose_name_plural': 'Announcement Ticker Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCalculatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='BSc. CSIT Eligibility Calculator', max_length=255, verbose_name='Calculator Heading')),
                ('sub_heading', models.TextField(default='Ensure your Grade 11 & 12 marks meet official university entrance rules before submitting your application.', verbose_name='Sub Heading Description')),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=2.2, max_digits=3, verbose_name='Minimum Required CGPA')),
                ('min_percentage', models.DecimalField(decimal_places=2, default=55.0, max_digits=5, verbose_name='Minimum Required Percentage (%)')),
                ('required_stream_text', models.CharField(default='Science Stream Mandatory: Physics & Mathematics background required in +2.', max_length=255, verbose_name='Stream Requirement Label')),
                ('eligible_message', models.TextField(default='Congratulations! Your score meets the entrance requirements for BSc. CSIT.', verbose_name='Pass/Eligible Message')),
                ('ineligible_message', models.TextField(default='Your score falls below the required threshold (minimum 2.2 CGPA or 55% in Grade 12 Science).', verbose_name='Ineligible Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Eligibility Calculator Rule',
                'verbose_name_plural': 'Eligibility Calculator Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('structured_data', models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)')),
                ('site_title', models.CharField(default='AIEMS — Ankur Institute of Engineering and Management Studies', max_length=255, verbose_name='Global Site Title')),
                ('primary_phone', models.CharField(default='9802113456', max_length=50, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Primary Hotline Number')),
                ('primary_email', models.CharField(default='info@aiems.edu.np', max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Primary Inquiry Email')),
                ('location_address', models.CharField(default='Bardibas, Mahottari, Nepal', max_length=255, verbose_name='Physical Campus Address')),
                ('map_iframe_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14251.652199859013!2d85.8902!3d26.9806!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39ec3f03a62886f3%3A0xc39cb7a32b62760!2sBardibas%2045700!5e0!3m2!1sen!2snp!4v1710000000000!5m2!1sen!2snp', verbose_name='Google Map Embed URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=home.models.site_settings_logo_path, validators=[home.models.validate_image_file], verbose_name='Main Site Header Logo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Global Site Setting',
                'verbose_name_plural': 'Global Site Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='topbanner',
            name='primary_btn_text',
            field=models.CharField(default='Apply For BSc. CSIT', max_length=100, verbose_name='Primary CTA Button Text'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='primary_btn_url',
            field=models.CharField(default='#admissions', max_length=255, verbose_name='Primary CTA Link'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='secondary_btn_text',
            field=models.CharField(default='Explore Syllabus & Modules', max_length=100, verbose_name='Secondary CTA Button Text'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='secondary_btn_url',
            field=models.CharField(default='#program', max_length=255, verbose_name='Secondary CTA Link'),
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Criteria Rule Description'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='dynamicpagecontent',
            name='content_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Structured Content (JSON)'),
        ),
        migrations.AlterField(
            model_name='dynamicpagecontent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='dynamicpagecontent',
            name='page_key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Page Key'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='branding_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Branding Description'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='footerconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.footer_logo_path, validators=[home.models.validate_image_file], verbose_name='Footer Logo'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open In New Tab'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Link Label'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL / Path'),
        ),
    ]
