# Generated by Django 5.0.3 on 2026-07-28 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_announcementtickeritem_eligibilitycalculatorconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityStreamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Stream / Program Option Name (e.g. Science Stream, BSc. CSIT)')),
                ('is_eligible', models.BooleanField(default=True, help_text='Check if students from this stream/program meet entrance prerequisites.', verbose_name='Is Eligible for Admission?')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('calculator_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_options', to='home.eligibilitycalculatorconfig', verbose_name='Calculator Parent Config')),
            ],
            options={
                'verbose_name': 'Academic Stream Option',
                'verbose_name_plural': 'Academic Stream Options',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
