# Generated by Django 5.0.3 on 2026-07-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_eligibilitystreamoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['category', 'display_order', '-created_at'], 'verbose_name': 'Footer Link', 'verbose_name_plural': 'Footer Links'},
        ),
        migrations.AddField(
            model_name='footerlink',
            name='category',
            field=models.CharField(choices=[('navigation', 'Navigation Column'), ('academics', 'Academics Column')], default='navigation', max_length=50, verbose_name='Footer Section / Column'),
        ),
        migrations.AddIndex(
            model_name='footerlink',
            index=models.Index(fields=['category'], name='home_footer_categor_1d2466_idx'),
        ),
    ]
