# Generated by Django 5.0.3 on 2026-07-28 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_footerlink_options_footerlink_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Menu Link Label')),
                ('url', models.CharField(max_length=500, verbose_name='URL / Route Path (e.g. /home, /about-us, #program)')),
                ('icon_class', models.CharField(default='fa-solid fa-house', max_length=100, verbose_name='FontAwesome / Icon Class (for Mobile Drawer & Special CTAs)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_button', models.BooleanField(default=False, verbose_name='Render as Action Button CTA?')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Open In New Tab?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('site_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_links', to='home.siteglobalsettings', verbose_name='Site Settings Parent')),
            ],
            options={
                'verbose_name': 'Header Navigation Link',
                'verbose_name_plural': 'Header Navigation Links',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='home_navbar_display_704046_idx'), models.Index(fields=['is_active'], name='home_navbar_is_acti_77f7e6_idx')],
            },
        ),
    ]
