# Generated by Django 5.0.3 on 2026-07-29 07:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_navbarlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbanner',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='aboutbanner',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='mail_id',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='admissioncontactdetail',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Criteria Rule Description'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='sub_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Content Label'),
        ),
        migrations.AlterField(
            model_name='admissiondetailtitle',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='announcementtickeritem',
            name='badge_label',
            field=models.CharField(blank=True, default='Notice', max_length=100, null=True, verbose_name='Badge Label'),
        ),
        migrations.AlterField(
            model_name='announcementtickeritem',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Action Link (Optional)'),
        ),
        migrations.AlterField(
            model_name='announcementtickeritem',
            name='text_content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Announcement Headline Copy'),
        ),
        migrations.AlterField(
            model_name='applycourse',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='applyforcoursebanner',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='applyforcoursebanner',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applyforpositionbanner',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='applyforpositionbanner',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='HR Contact Number'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='mail_id',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='HR Email'),
        ),
        migrations.AlterField(
            model_name='applyjobdetail',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='applyposition',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Cover Message'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='campustitle',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='dynamicpagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Page Title'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='eligible_message',
            field=models.TextField(blank=True, default='Congratulations! Your score meets the entrance requirements for BSc. CSIT.', null=True, verbose_name='Pass/Eligible Message'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='heading',
            field=models.CharField(blank=True, default='BSc. CSIT Eligibility Calculator', max_length=255, null=True, verbose_name='Calculator Heading'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='ineligible_message',
            field=models.TextField(blank=True, default='Your score falls below the required threshold (minimum 2.2 CGPA or 55% in Grade 12 Science).', null=True, verbose_name='Ineligible Message'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='min_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.2, max_digits=3, null=True, verbose_name='Minimum Required CGPA'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='min_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=55.0, max_digits=5, null=True, verbose_name='Minimum Required Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='required_stream_text',
            field=models.CharField(blank=True, default='Science Stream Mandatory: Physics & Mathematics background required in +2.', max_length=255, null=True, verbose_name='Stream Requirement Label'),
        ),
        migrations.AlterField(
            model_name='eligibilitycalculatorconfig',
            name='sub_heading',
            field=models.TextField(blank=True, default='Ensure your Grade 11 & 12 marks meet official university entrance rules before submitting your application.', null=True, verbose_name='Sub Heading Description'),
        ),
        migrations.AlterField(
            model_name='eligibilitystreamoption',
            name='calculator_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_options', to='home.eligibilitycalculatorconfig', verbose_name='Calculator Parent Config'),
        ),
        migrations.AlterField(
            model_name='eligibilitystreamoption',
            name='is_eligible',
            field=models.BooleanField(default=True, verbose_name='Is Eligible for Admission?'),
        ),
        migrations.AlterField(
            model_name='eligibilitystreamoption',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stream / Program Option Name'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='home.faqcategory', verbose_name='Category Parent'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='category',
            field=models.CharField(blank=True, choices=[('navigation', 'Navigation Column'), ('academics', 'Academics Column')], default='navigation', max_length=50, null=True, verbose_name='Footer Section / Column'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='footer_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='home.footerconfig', verbose_name='Footer Configuration Parent'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Label'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL / Path'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='icon_class',
            field=models.CharField(blank=True, default='fa-solid fa-house', max_length=100, null=True, verbose_name='FontAwesome / Icon Class'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Link Label'),
        ),
        migrations.AlterField(
            model_name='navbarlink',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL / Route Path'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='program',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.program_icon_path, validators=[home.models.validate_image_file], verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='sub_content',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Content Summary'),
        ),
        migrations.AlterField(
            model_name='programtitle',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='programtitle',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='siteglobalsettings',
            name='location_address',
            field=models.CharField(blank=True, default='Bardibas, Mahottari, Nepal', max_length=255, null=True, verbose_name='Physical Campus Address'),
        ),
        migrations.AlterField(
            model_name='siteglobalsettings',
            name='map_iframe_url',
            field=models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14251.652199859013!2d85.8902!3d26.9806!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39ec3f03a62886f3%3A0xc39cb7a32b62760!2sBardibas%2045700!5e0!3m2!1sen!2snp!4v1710000000000!5m2!1sen!2snp', null=True, verbose_name='Google Map Embed URL'),
        ),
        migrations.AlterField(
            model_name='siteglobalsettings',
            name='primary_email',
            field=models.CharField(blank=True, default='info@aiems.edu.np', max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Primary Inquiry Email'),
        ),
        migrations.AlterField(
            model_name='siteglobalsettings',
            name='primary_phone',
            field=models.CharField(blank=True, default='9802113456', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be valid format (7 to 20 digits, optionally starting with +).', regex='^\\+?1?\\d{7,20}$')], verbose_name='Primary Hotline Number'),
        ),
        migrations.AlterField(
            model_name='siteglobalsettings',
            name='site_title',
            field=models.CharField(blank=True, default='AIEMS — Ankur Institute of Engineering and Management Studies', max_length=255, null=True, verbose_name='Global Site Title'),
        ),
        migrations.AlterField(
            model_name='teamfaculty',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='teamfaculty',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Designation Title'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='message',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Leadership Message Statement'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='teamtitle',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='teamtitle',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.top_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='primary_btn_text',
            field=models.CharField(blank=True, default='Apply For BSc. CSIT', max_length=100, null=True, verbose_name='Primary CTA Button Text'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='primary_btn_url',
            field=models.CharField(blank=True, default='#admissions', max_length=255, null=True, verbose_name='Primary CTA Link'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='secondary_btn_text',
            field=models.CharField(blank=True, default='Explore Syllabus & Modules', max_length=100, null=True, verbose_name='Secondary CTA Button Text'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='secondary_btn_url',
            field=models.CharField(blank=True, default='#program', max_length=255, null=True, verbose_name='Secondary CTA Link'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='sub_heading',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Heading'),
        ),
        migrations.CreateModel(
            name='HeroTechnicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, default='fa-solid fa-building-columns', max_length=100, null=True, verbose_name='FontAwesome / Icon Class')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tag Label Text')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('top_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_tags', to='home.topbanner', verbose_name='Parent Hero Banner')),
            ],
            options={
                'verbose_name': 'Hero Technical Tag',
                'verbose_name_plural': 'Hero Technical Tags',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Target Number for Animated Counter')),
                ('prefix', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name="Value Prefix (e.g. '1st', '$')")),
                ('suffix', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name="Value Suffix (e.g. '%', '+')")),
                ('label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Primary Metric Label')),
                ('sub_label', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sub Label / Description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('top_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_stats', to='home.topbanner', verbose_name='Parent Hero Banner')),
            ],
            options={
                'verbose_name': 'Landing Stat / Counter Metric',
                'verbose_name_plural': 'Landing Stats / Counter Metrics',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
