# Generated by Django 5.0.3 on 2026-07-29 12:41

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_aboutbanner_content_alter_aboutbanner_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutbanner',
            name='icon_class',
            field=models.CharField(blank=True, default='fa-solid fa-circle-check', max_length=100, null=True, verbose_name='FontAwesome / Icon Class'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='badge_text',
            field=models.CharField(blank=True, default='Brand New Technical Institute', max_length=255, null=True, verbose_name='Section Badge Label'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='content_paragraph_2',
            field=models.TextField(blank=True, default='In our founding year, we are offering the BSc. CSIT program under university affiliation. Our mission is to train students in fundamental computer science, software development, data structures, and computer networks through intensive lab work.', null=True, verbose_name='Secondary Narrative Paragraph (Paragraph 2)'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='floating_badge_icon_class',
            field=models.CharField(blank=True, default='fa-solid fa-microchip', max_length=100, null=True, verbose_name='Floating Badge Icon Class'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='floating_badge_subtitle',
            field=models.CharField(blank=True, default='Purpose-built for Computer Science', max_length=255, null=True, verbose_name='Floating Badge Subtext'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='floating_badge_title',
            field=models.CharField(blank=True, default='Pure Technical Focus', max_length=255, null=True, verbose_name='Floating Badge Headline'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.about_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Featured Section Image'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='primary_btn_text',
            field=models.CharField(blank=True, default='Explore BSc. CSIT Course', max_length=100, null=True, verbose_name='Primary CTA Button Text'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='primary_btn_url',
            field=models.CharField(blank=True, default='#program', max_length=255, null=True, verbose_name='Primary CTA Link'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='secondary_btn_text',
            field=models.CharField(blank=True, default='Contact Admissions Desk', max_length=100, null=True, verbose_name='Secondary CTA Link Text'),
        ),
        migrations.AddField(
            model_name='aboutbannertitle',
            name='secondary_btn_url',
            field=models.CharField(blank=True, default='#contact', max_length=255, null=True, verbose_name='Secondary CTA Link URL'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='heading',
            field=models.CharField(blank=True, default='Setting New Standards for Computer Science Education in Bardibas', max_length=255, null=True, verbose_name='Main Headline'),
        ),
        migrations.AlterField(
            model_name='aboutbannertitle',
            name='sub_heading',
            field=models.TextField(blank=True, default='Ankur Institute of Engineering and Management Studies (AIEMS) is a newly established technical college dedicated exclusively to computer science and information technology education.', null=True, verbose_name='Primary Narrative Paragraph (Paragraph 1)'),
        ),
    ]
