# Generated by Django 5.0.3 on 2026-07-30 06:45

import django.db.models.deletion
import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_aboutbanner_icon_class_aboutbannertitle_badge_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedHomeShowcaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('structured_data', models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)')),
                ('heading', models.CharField(default='BSc. CSIT', max_length=255, verbose_name='Showcase Degree Title')),
                ('sub_content', models.TextField(blank=True, null=True, verbose_name='Main Narrative Copy')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=home.models.top_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Full-Height Left Banner Image')),
                ('status_badge_text', models.CharField(blank=True, default='Now Accepting Applications', max_length=100, null=True, verbose_name='Status Badge Text')),
                ('cohort_tag', models.CharField(blank=True, default='Inaugural Cohort', max_length=100, null=True, verbose_name='Cohort Tag')),
                ('charter_badge_tag', models.CharField(blank=True, default='Rajarshi Janak University Affiliated Institution', max_length=255, null=True, verbose_name='Affiliation Charter Tag')),
                ('specializations_title', models.CharField(blank=True, default='Core Technical Specializations', max_length=255, null=True, verbose_name='Specializations Section Headline')),
                ('prerequisite_title', models.CharField(blank=True, default='Entry Prerequisites (+2 Science)', max_length=255, null=True, verbose_name='Prerequisites Box Title')),
                ('prerequisite_overview', models.TextField(blank=True, null=True, verbose_name='Prerequisites Callout Paragraph')),
                ('apply_button_text', models.CharField(blank=True, default='Apply For BSc. CSIT', max_length=100, null=True, verbose_name='Apply Button Label')),
                ('eligibility_button_text', models.CharField(blank=True, default='Check Your Eligibility', max_length=100, null=True, verbose_name='Eligibility Button Label')),
                ('syllabus_button_text', models.CharField(blank=True, default='View Full Syllabus', max_length=100, null=True, verbose_name='Syllabus Button Label')),
                ('custom_syllabus_redirect_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Custom Syllabus Link URL (Optional Override)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('program_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isolated_showcase_cards', to='home.programtitle', verbose_name='Parent Section Title')),
                ('target_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_target_referrers', to='home.program', verbose_name='Target Program (Syllabus Link Target)')),
            ],
            options={
                'verbose_name': 'Homepage Program Showcase Card (Isolated)',
                'verbose_name_plural': 'Homepage Program Showcase Cards (Isolated)',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IsolatedHomeShowcaseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Feature Pill Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Feature Pill Subtext')),
                ('icon_class', models.CharField(default='fa-solid fa-code', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('showcase_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolated_features', to='home.isolatedhomeshowcasecard', verbose_name='Parent Isolated Showcase Card')),
            ],
            options={
                'verbose_name': 'Isolated Showcase Feature Pill',
                'verbose_name_plural': 'Isolated Showcase Feature Pills',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IsolatedHomeShowcaseRequirementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Prerequisite Rule Sentence')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('showcase_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolated_requirements', to='home.isolatedhomeshowcasecard', verbose_name='Parent Isolated Showcase Card')),
            ],
            options={
                'verbose_name': 'Isolated Showcase Prerequisite Rule',
                'verbose_name_plural': 'Isolated Showcase Prerequisite Rules',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IsolatedHomeShowcaseSummaryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Metric Label (e.g. Duration)')),
                ('value', models.CharField(max_length=255, verbose_name='Highlight Value (e.g. 4 Years)')),
                ('sub_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Sub label (e.g. 8 Semesters)')),
                ('icon_class', models.CharField(default='fa-solid fa-clock', max_length=100, verbose_name='FontAwesome Icon Class')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('showcase_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolated_summary_points', to='home.isolatedhomeshowcasecard', verbose_name='Parent Isolated Showcase Card')),
            ],
            options={
                'verbose_name': 'Isolated Showcase Metric Point',
                'verbose_name_plural': 'Isolated Showcase Metric Points',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
