# Generated by Django 5.0.3 on 2026-07-30 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_isolatedhomeshowcasecard_isolatedhomeshowcasefeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Global Notification Configuration', max_length=255, verbose_name='Configuration Profile Name')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable email notification dispatches across all forms on the site.', verbose_name='Is Active Globally?')),
                ('provider', models.CharField(choices=[('smtp', 'Custom SMTP'), ('gmail', 'Gmail SMTP'), ('outlook', 'Outlook / Office 365')], default='smtp', max_length=50, verbose_name='Email Provider Scheme')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Server Host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Network Port')),
                ('encryption', models.CharField(choices=[('tls', 'STARTTLS (Explicit TLS)'), ('ssl', 'SSL/TLS'), ('none', 'None (Plain)')], default='tls', max_length=20, verbose_name='Encryption Protocol')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP Handshake Username / Email')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP Password / App Credential')),
                ('default_from_email', models.EmailField(default='info@aiems.edu.np', max_length=254, verbose_name='Default From Email Envelope Address')),
                ('default_sender_name', models.CharField(default='AIEMS Admissions & HR Desk', max_length=255, verbose_name='Default Sender Display Name')),
                ('primary_admin_email', models.EmailField(default='admissions@aiems.edu.np', help_text='Dedicated primary college email address to receive submission notifications.', max_length=254, verbose_name='Primary Admin Notification Email')),
                ('secondary_admin_email', models.EmailField(blank=True, default='', help_text='Optional secondary college email address for CC/alert notifications.', max_length=254, verbose_name='Secondary Admin Notification Email (Optional)')),
                ('send_applicant_confirmation', models.BooleanField(default=True, verbose_name='Send Confirmation Email to Applicants?')),
                ('send_admin_notification', models.BooleanField(default=True, verbose_name='Send Alert Email to College Admin Team?')),
                ('course_app_subject', models.CharField(default='Application Received: {program} at AIEMS', max_length=255, verbose_name='Course Application Subject Template')),
                ('course_app_applicant_body', models.TextField(default='Thank you for applying to AIEMS. We have received your application details for the program. Our admissions counseling desk will review your submission and contact you shortly.', verbose_name='Course Application Applicant Message Body')),
                ('job_app_subject', models.CharField(default='Application Received for {position} - AIEMS', max_length=255, verbose_name='Job Application Subject Template')),
                ('job_app_applicant_body', models.TextField(default='Thank you for submitting your career application. Your resume and credentials have been delivered to our HR department for evaluation.', verbose_name='Job Application Applicant Message Body')),
                ('contact_subject', models.CharField(default='Inquiry Received - AIEMS Bardibas', max_length=255, verbose_name='Contact Inquiry Subject Template')),
                ('contact_applicant_body', models.TextField(default='Thank you for reaching out to AIEMS. We have received your inquiry message and our administration team will contact you soon.', verbose_name='Contact Inquiry Applicant Message Body')),
                ('timeout', models.PositiveIntegerField(default=15, verbose_name='Connection Timeout Threshold (Seconds)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
