# Generated by Django 5.0.3 on 2026-07-30 13:33

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='email_footer_address',
            field=models.CharField(blank=True, default='Bardibas, Mahottari, Nepal', max_length=255, null=True, verbose_name='Email Footer Physical Address'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_footer_text',
            field=models.CharField(blank=True, default='Ankur Institute of Engineering and Management Studies (AIEMS)', max_length=255, null=True, verbose_name='Email Footer Institution Name'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_header_bg_color',
            field=models.CharField(blank=True, default='#0e0e54', help_text='Primary background color for the email banner header (e.g., #0e0e54 or #009444).', max_length=50, null=True, verbose_name='Email Header Accent Color (Hex)'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='email_logo',
            field=models.ImageField(blank=True, help_text='Dedicated graphic logo used at the top of outgoing emails. Recommended size: PNG or WEBP up to 300px wide.', null=True, upload_to=home.models.email_logo_path, validators=[home.models.validate_image_file], verbose_name='Email Template Header Logo'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='next_steps_body',
            field=models.TextField(blank=True, default='Our counseling team will verify your academic background and reach out with details regarding entrance schedules and fee structures.', null=True, verbose_name="Course Confirmation 'Next Steps' Box Content"),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='next_steps_heading',
            field=models.CharField(blank=True, default='What Happens Next?', max_length=255, null=True, verbose_name="Course Confirmation 'Next Steps' Box Title"),
        ),
    ]
