# Generated by Django 5.0.3 on 2026-07-30 15:16

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_notificationsetting_email_footer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='email_logo',
            field=models.ImageField(blank=True, help_text='Dedicated raster (JPG/JPEG/PNG/WEBP) logo used at the top of outgoing emails. Recommended size: PNG up to 300px wide. SVG is not allowed because email clients cannot render it inline reliably.', null=True, upload_to=home.models.email_logo_path, validators=[home.models.validate_email_image_file], verbose_name='Email Template Header Logo'),
        ),
    ]
