# Generated by Django 5.0.3 on 2026-08-02 09:50

import django.utils.timezone
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_notificationsetting_email_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePopupBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Primary SEO title tag. Recommended length: 50-60 characters.', max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description tag. Recommended length: 150-160 characters.', null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search engine targeting.', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('structured_data', models.JSONField(blank=True, help_text='Valid JSON-LD block representing structured metadata schema.', null=True, verbose_name='Structured Data (Schema.org / JSON-LD)')),
                ('heading', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Popup Banner Heading / Title')),
                ('sub_heading', models.TextField(blank=True, default='', null=True, verbose_name='Sub Heading / Short Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.popup_banner_image_path, validators=[home.models.validate_image_file], verbose_name='Popup Image / Flyer Asset (Flexible Size & Aspect Ratio)')),
                ('action_url', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Click-through CTA URL / Link')),
                ('button_text', models.CharField(blank=True, default='Apply Now', max_length=100, null=True, verbose_name='CTA Button Label')),
                ('show_cta_button', models.BooleanField(default=True, verbose_name='Show Action CTA Button?')),
                ('start_date', models.DateTimeField(blank=True, help_text='If set, popup will only display on or after this timestamp.', null=True, verbose_name='Publish Start Timestamp (Optional)')),
                ('end_date', models.DateTimeField(blank=True, help_text='If set, popup will automatically stop displaying after this timestamp.', null=True, verbose_name='Publish Expiry Timestamp (Optional)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Priority Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Homepage Popup Banner',
                'verbose_name_plural': 'Homepage Popup Banners',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['display_order'], name='home_homepa_display_cf0e04_idx'), models.Index(fields=['is_active'], name='home_homepa_is_acti_b745a5_idx'), models.Index(fields=['-created_at'], name='home_homepa_created_fcc2a1_idx')],
            },
        ),
    ]
